sonar.organization=bebie-sbb
sonar.projectKey=bebie-sbb_sbb-backend
sonar.projectName=SBB Backend
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**
sonar.go.coverage.reportPaths=coverage.out
sonar.qualitygate.wait=true
